{{- if and .Values.serviceAccount.create ((.Values.autoUnseal).enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "signet.fullname" . }}-unseal-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "signet.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "signet.fullname" . }}-unseal-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "signet.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
