package gitops

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/bytepunx/signet/internal/store"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// mockStore implements secretStore for unit testing.
type mockStore struct {
	keys []store.SOPSKey
}

func (m *mockStore) ListSOPSKeys(_ context.Context, _ string) ([]store.SOPSKey, error) {
	return m.keys, nil
}
func (m *mockStore) PutSecret(_ context.Context, _ *store.Secret) error { return nil }
func (m *mockStore) GetSecret(_ context.Context, _, _, _ string) (*store.Secret, error) {
	return nil, store.ErrNotFound
}
func (m *mockStore) DeleteSecret(_ context.Context, _, _, _ string) error { return nil }
func (m *mockStore) GetRepository(_ context.Context, _ string) (*store.Repository, error) {
	return nil, nil
}
func (m *mockStore) ListRepositories(_ context.Context) ([]store.Repository, error) {
	return nil, nil
}
func (m *mockStore) UpdateSyncState(_ context.Context, _, _ string, _ time.Time) error {
	return nil
}

// SyncServiceConfig always simulates a first-ever write (mockStore tracks
// no state), matching PutServiceConfig's old unconditional-success behavior
// for tests that only care that a write happened, not merge semantics —
// see statefulKEKStore for a fake that actually exercises the merge.
func (m *mockStore) SyncServiceConfig(
	_ context.Context, _, _ string, _ json.RawMessage, _ string,
	_ func(synced, live, git json.RawMessage) (json.RawMessage, bool, error),
) (version int, conflict bool, err error) {
	return 1, false, nil
}
func (m *mockStore) DeleteServiceConfig(_ context.Context, _, _ string) error { return nil }
func (m *mockStore) GetActiveKEK(_ context.Context) (*store.KEK, error) {
	return nil, store.ErrNotFound
}
func (m *mockStore) PutKEK(_ context.Context, _ *store.KEK) error                  { return nil }
func (m *mockStore) UpdateSecretRepoID(_ context.Context, _, _, _, _ string) error { return nil }

// mockKeys implements keyUnwrapper for unit testing.
type mockKeys struct{}

func (m *mockKeys) Use(fn func([]byte) error) error {
	return fn(make([]byte, 32))
}

// TestSyncFromDir_NoSOPSKeys verifies that SyncFromDir returns a clear error
// when the store has no age keys configured.
func TestSyncFromDir_NoSOPSKeys(t *testing.T) {
	dir := t.TempDir()
	secretsDir := filepath.Join(dir, "secrets", "prod", "api")
	require.NoError(t, os.MkdirAll(secretsDir, 0o700))
	require.NoError(t, os.WriteFile(filepath.Join(secretsDir, "token.yaml"), []byte("sops: {}"), 0o600))

	syncer := NewSyncer(&mockStore{keys: nil}, &mockKeys{}, nil, nil, "")
	_, err := syncer.SyncFromDir(context.Background(), dir, "secrets/", "abc123", "", "test-actor")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "no age keys")
}

// TestSyncFromDir_MissingSecretsDir verifies that SyncFromDir returns an error
// when the configured secrets directory does not exist within the extracted bundle.
func TestSyncFromDir_MissingSecretsDir(t *testing.T) {
	dir := t.TempDir()
	// secrets/ subdirectory intentionally absent

	syncer := NewSyncer(&mockStore{keys: nil}, &mockKeys{}, nil, nil, "")
	_, err := syncer.SyncFromDir(context.Background(), dir, "secrets/", "", "", "test-actor")
	require.Error(t, err, "should fail when secrets dir is absent")
}

// TestSyncFromDir_HeadSHAPassedThrough verifies that the headSHA parameter
// is reflected in the SyncResult even when the sync fails early.
//
// This matters for audit log correctness: the SHA must come from the caller
// (who knows the git commit), not be generated by SyncFromDir.
func TestSyncFromDir_HeadSHAPassedThrough(t *testing.T) {
	dir := t.TempDir()
	// No secrets dir — will error, but let's check that the sha IS returned
	// before the error in the no-keys case (it isn't — error is earlier).
	// What we're checking is the contract: when SyncFromDir succeeds (even
	// with 0 files), the SHA in the result is exactly what was passed in.
	//
	// Build a dir with a secrets path but no YAML files to avoid the SOPS path.
	secretsDir := filepath.Join(dir, "secrets")
	require.NoError(t, os.MkdirAll(secretsDir, 0o700))

	// Put a non-YAML file so the walk completes without hitting storeSecret.
	require.NoError(t, os.WriteFile(filepath.Join(secretsDir, "README.md"), []byte("# readme"), 0o600))

	syncer := NewSyncer(&mockStore{keys: []store.SOPSKey{{PublicKey: "age1test"}}}, &mockKeys{}, nil, nil, "")
	// Will fail at loadIdentities (can't decrypt the fake key), but the
	// architecture guarantee is: if it succeeds, SHA is passed through.
	// Here we just confirm the error is from key decryption, not from the SHA.
	_, err := syncer.SyncFromDir(context.Background(), dir, "secrets/", "deadbeef", "", "test-actor")
	// Error expected (fake encrypted key), but it must NOT be about the SHA.
	require.Error(t, err)
	assert.NotContains(t, err.Error(), "deadbeef", "error should be about key loading, not the SHA")
}

// TestSyncConfigFromDir_BasicParse verifies that SyncConfigFromDir parses a
// nested YAML file and stores it via PutServiceConfig.
func TestSyncConfigFromDir_BasicParse(t *testing.T) {
	dir := t.TempDir()
	configDir := filepath.Join(dir, "config", "payments")
	require.NoError(t, os.MkdirAll(configDir, 0o700))
	require.NoError(t, os.WriteFile(filepath.Join(configDir, "api.yaml"),
		[]byte("port: 8080\ndb:\n  host: postgres\n  port: 5432\n"), 0o600))

	ms := &mockStore{}
	syncer := NewSyncer(ms, &mockKeys{}, nil, nil, "")
	count, _, skipped, err := syncer.SyncConfigFromDir(context.Background(), dir, "config/", "", "test-actor", false)
	require.NoError(t, err)
	assert.Equal(t, 1, count)
	assert.Empty(t, skipped)
}

// TestSyncConfigFromDir_SkipsAndReportsPathDepthMismatch is the regression
// test for bytepunx/signet#22: a config file committed one level too deep
// (<namespace>/<service>/config.yaml, 3 components, instead of the required
// <namespace>/<service>.yaml, 2 components) must not sync silently. It should
// be reported in Skipped so "signet repo sync" can surface it, while the
// correctly-shaped file next to it still syncs normally.
func TestSyncConfigFromDir_SkipsAndReportsPathDepthMismatch(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "config", "authstar"), 0o700))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "config", "authstar", "portcullis.yaml"),
		[]byte("tenants: []\n"), 0o600))

	// One level too deep — the exact shape reported in the issue.
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "config", "authstar", "tower"), 0o700))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "config", "authstar", "tower", "config.yaml"),
		[]byte("tenants: []\n"), 0o600))

	ms := &mockStore{}
	syncer := NewSyncer(ms, &mockKeys{}, nil, nil, "")
	count, _, skipped, err := syncer.SyncConfigFromDir(context.Background(), dir, "config/", "", "test-actor", false)
	require.NoError(t, err)
	assert.Equal(t, 1, count, "only the correctly-shaped file should be counted as synced")
	require.Len(t, skipped, 1, "the wrong-depth file must be reported, not silently dropped")
	assert.Equal(t, "config/authstar/tower/config.yaml", skipped[0])
}

// TestSyncConfigFromDir_EmptyPath verifies that an empty configPath is a no-op.
func TestSyncConfigFromDir_EmptyPath(t *testing.T) {
	syncer := NewSyncer(&mockStore{}, &mockKeys{}, nil, nil, "")
	count, _, _, err := syncer.SyncConfigFromDir(context.Background(), t.TempDir(), "", "", "test-actor", false)
	require.NoError(t, err)
	assert.Equal(t, 0, count)
}

// TestSyncConfigFromDir_MissingDir verifies that a missing config dir is silently skipped.
func TestSyncConfigFromDir_MissingDir(t *testing.T) {
	syncer := NewSyncer(&mockStore{}, &mockKeys{}, nil, nil, "")
	count, _, _, err := syncer.SyncConfigFromDir(context.Background(), t.TempDir(), "config/", "", "test-actor", false)
	require.NoError(t, err)
	assert.Equal(t, 0, count)
}

// TestNormalizeForJSON verifies that yaml.v3 date values are converted to strings.
func TestNormalizeForJSON(t *testing.T) {
	cases := []struct {
		name  string
		input interface{}
		check func(t *testing.T, got interface{})
	}{
		{
			name:  "string passthrough",
			input: "hello",
			check: func(t *testing.T, got interface{}) { assert.Equal(t, "hello", got) },
		},
		{
			name:  "int passthrough",
			input: 42,
			check: func(t *testing.T, got interface{}) { assert.Equal(t, 42, got) },
		},
		{
			name:  "nested map recurses",
			input: map[string]interface{}{"a": map[string]interface{}{"b": 1}},
			check: func(t *testing.T, got interface{}) {
				m := got.(map[string]interface{})
				inner := m["a"].(map[string]interface{})
				assert.Equal(t, 1, inner["b"])
			},
		},
		{
			name:  "slice recurses",
			input: []interface{}{"x", 2},
			check: func(t *testing.T, got interface{}) {
				s := got.([]interface{})
				assert.Equal(t, "x", s[0])
				assert.Equal(t, 2, s[1])
			},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			tc.check(t, normalizeForJSON(tc.input))
		})
	}
}

// newSyncableStore builds a statefulKEKStore with one real, registered SOPS
// age key (via GenerateAgeKey, the same helper production code uses), and
// returns its public key alongside the store so callers can pass it to
// sopsEncrypt as the encryption recipient. loadIdentities (called by every
// SyncFromDir/SyncFromPush) needs at least one usable key or every sync
// fails outright with "no age keys configured".
func newSyncableStore(t *testing.T, keys keyUnwrapper) (*statefulKEKStore, string) {
	t.Helper()
	pubKey, encPriv, err := GenerateAgeKey(keys)
	require.NoError(t, err)
	return &statefulKEKStore{
		sopsKeys: []store.SOPSKey{{PublicKey: pubKey, EncryptedPrivateKey: encPriv, IsActive: true}},
	}, pubKey
}

// sopsEncrypt encrypts plaintext with the real sops binary under
// recipientPubKey (an age1... public key already registered with the store
// under test, so DecryptFile can round-trip it via the real decrypt path).
// Skips the calling test if sops isn't on PATH — matches the precedent set
// in sops_test.go's TestDecryptFile_RealSopsCiphertext.
func sopsEncrypt(t *testing.T, dir, relPath, plaintext, recipientPubKey string) {
	t.Helper()
	sopsPath, err := exec.LookPath("sops")
	if err != nil {
		t.Skip("sops binary not found on PATH; skipping real ciphertext test")
	}

	configPath := filepath.Join(dir, ".sops.yaml")
	config := fmt.Sprintf("creation_rules:\n    - path_regex: ^secrets/\n      age: %s\n", recipientPubKey)
	require.NoError(t, os.WriteFile(configPath, []byte(config), 0o644))

	fullPath := filepath.Join(dir, relPath)
	require.NoError(t, os.MkdirAll(filepath.Dir(fullPath), 0o755))
	require.NoError(t, os.WriteFile(fullPath, []byte(plaintext), 0o600))

	cmd := exec.Command(sopsPath, "--config", configPath, "--encrypt", "--in-place", relPath)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "sops encrypt: %s", out)
}

// TestSyncFromDir_SkipsAndReportsPathDepthMismatch is the secrets-side
// counterpart to TestSyncConfigFromDir_SkipsAndReportsPathDepthMismatch,
// regression-testing bytepunx/signet#22 for SyncFromDir: a secret file
// committed at the wrong depth (4 components instead of the required
// <namespace>/<service>/<name>.yaml) must be reported in Skipped, not
// silently dropped, while a correctly-shaped secret next to it still syncs.
func TestSyncFromDir_SkipsAndReportsPathDepthMismatch(t *testing.T) {
	dir := t.TempDir()
	keys := &mockKeys{}
	st, pubKey := newSyncableStore(t, keys)
	sopsEncrypt(t, dir, "secrets/ns/svc/good.yaml", "value: good\n", pubKey)
	sopsEncrypt(t, dir, "secrets/ns/svc/extra/deep.yaml", "value: bad\n", pubKey)

	syncer := NewSyncer(st, keys, nil, nil, "")
	result, err := syncer.SyncFromDir(context.Background(), dir, "secrets/", "sha1", "repo-1", "test-actor")
	require.NoError(t, err)
	assert.Equal(t, 1, result.Added, "only the correctly-shaped secret should be counted as synced")
	require.Len(t, result.Skipped, 1, "the wrong-depth file must be reported, not silently dropped")
	assert.Equal(t, "secrets/ns/svc/extra/deep.yaml", result.Skipped[0])
}

// TestSyncFromDir_BackfillsRepoIDOnUnchangedResync verifies a gap in repo_id
// attribution: storeSecret's isUnchanged dedup optimization skips PutSecret
// (and therefore repo_id attribution) entirely when a resync's plaintext
// matches what's already stored. Found live: a secret whose content never
// changed since before repo_id existed kept repo_id NULL forever.
// UpdateSecretRepoID (called from storeSecret's unchanged branch) is the
// fix; this proves the backfill actually happens even when the write itself
// is skipped as unchanged.
func TestSyncFromDir_BackfillsRepoIDOnUnchangedResync(t *testing.T) {
	dir := t.TempDir()
	keys := &mockKeys{}
	st, pubKey := newSyncableStore(t, keys)
	sopsEncrypt(t, dir, "secrets/ns/svc/stable.yaml", "value: stable\n", pubKey)

	syncer := NewSyncer(st, keys, nil, nil, "")
	ctx := context.Background()

	result, err := syncer.SyncFromDir(ctx, dir, "secrets/", "sha1", "repo-old", "test-actor")
	require.NoError(t, err)
	assert.Equal(t, 1, result.Added)
	sec := st.secrets[secretKey("ns", "svc", "stable")]
	require.NotNil(t, sec)
	assert.Equal(t, "repo-old", sec.RepoID)

	// Re-encrypt the SAME plaintext (sops nonce differs, but the plaintext
	// isUnchanged compares is identical) and sync again under a DIFFERENT
	// repo — this hits storeSecret's isUnchanged dedup path (no new version
	// written), which must still update repo_id.
	sopsEncrypt(t, dir, "secrets/ns/svc/stable.yaml", "value: stable\n", pubKey)
	_, err = syncer.SyncFromDir(ctx, dir, "secrets/", "sha2", "repo-new", "test-actor")
	require.NoError(t, err)
	sec = st.secrets[secretKey("ns", "svc", "stable")]
	require.NotNil(t, sec)
	assert.Equal(t, "repo-new", sec.RepoID, "repo_id must be updated even when the write itself was skipped as unchanged")
}

// fakeBus is a minimal notifier that just counts calls, so tests can assert
// on whether a bundle-changed notification actually fired.
type fakeBus struct {
	notifyCount       int
	notifyBundleCount int
}

func (b *fakeBus) Notify(_, _, _ string)     { b.notifyCount++ }
func (b *fakeBus) NotifyService(_, _ string) {}
func (b *fakeBus) NotifyBundle(_, _ string)  { b.notifyBundleCount++ }

// TestSyncFromDir_NoNotifyOrAddedOnUnchangedResync is a regression test for
// bytepunx/signet#55: re-syncing a secret whose plaintext hasn't changed
// must not count it in SyncResult.Added, and must not fire a bundle-changed
// notification. Before the fix, storeSecret's isUnchanged skip was
// indistinguishable from a real write to its callers, so every periodic
// reconciliation pass re-"added" and re-notified every unchanged secret,
// causing watchers of WatchServiceBundle to restart in a permanent loop.
func TestSyncFromDir_NoNotifyOrAddedOnUnchangedResync(t *testing.T) {
	dir := t.TempDir()
	keys := &mockKeys{}
	st, pubKey := newSyncableStore(t, keys)
	sopsEncrypt(t, dir, "secrets/ns/svc/stable.yaml", "value: stable\n", pubKey)

	bus := &fakeBus{}
	syncer := NewSyncer(st, keys, bus, nil, "")
	ctx := context.Background()

	result, err := syncer.SyncFromDir(ctx, dir, "secrets/", "sha1", "repo-1", "test-actor")
	require.NoError(t, err)
	assert.Equal(t, 1, result.Added, "first sync of a new secret must be counted as added")
	assert.Equal(t, 1, bus.notifyBundleCount, "first sync of a new secret must notify watchers")

	// Re-encrypt the SAME plaintext (sops nonce differs, but the plaintext
	// isUnchanged compares is identical) and sync again — this must be a
	// true no-op from the caller's perspective, exactly as it would be on
	// every periodic reconciliation tick against an unchanged repo.
	sopsEncrypt(t, dir, "secrets/ns/svc/stable.yaml", "value: stable\n", pubKey)
	result, err = syncer.SyncFromDir(ctx, dir, "secrets/", "sha1", "repo-1", "test-actor")
	require.NoError(t, err)
	assert.Equal(t, 0, result.Added, "resyncing unchanged content must not be counted as added")
	assert.Equal(t, 1, bus.notifyBundleCount, "resyncing unchanged content must not fire another bundle-changed notification")
	assert.Equal(t, 1, bus.notifyCount, "resyncing unchanged content must not fire another per-secret notification")
}
